### ISSUE TITLE
Adding support for Flags 

### ISSUE THREAD

**Issue by frankodoom** [frankodoom/CountryData.Net#16]
I have been experimenting with country flags in sprite and SVG formats, the idea is to allow web and mobile developers to display country data with their corresponding flags. I am thinking SVG and sprites because we don't want to increase the size of the library by a huge chunk.

**Comment by frankodoom** [comment]
Found an open source project called [flag-icons](https://flagicons.lipis.dev/) which has 1x1 and 4x4 svg flags. We might probably have to redesign the fetching of country data to include an optional `.AddFlags()`, maybe change the Country Helper implementation to a builder pattern? so we can chain in some options.

**Comment by sadranyi** [comment]
How about ASCII that should be lightweight

**Comment by DamienDoumer** [comment]
@frankodoom Why not use emoji flags? They are universal and are lightweight too.

**Comment by DamienDoumer** [comment]
And by the way, iso country codes could be encoded to emoji flags. This could be used in XAML or other C# front end frameworks to display the country flag

**Comment by frankodoom** [comment]
@sadranyi @DamienDoumer  we need to experiment how they will render in mobile and web. The idea was to get developers to easily build country selections with flags.
![flags](https://user-images.githubusercontent.com/10815235/167263124-7730b3cb-c164-4009-a754-5e17ed9ce6a9.png)

**Comment by DamienDoumer** [comment]
@frankodoom Do you need the sample app added into the project's sample ?

**Comment by frankodoom** [comment]
@DamienDoumer yes this will be great.:-)

**Comment by DamienDoumer** [comment]
Ok, I'm on it.
