### ISSUE TITLE
Any  plan to add currency code

### ISSUE THREAD

**Issue by ikeliec** [frankodoom/CountryData.Net#24]
Hi, I am working on a project that needs me to get the currency code of countries from a dropdown list of countries.

I must commend the effort that has been put into this library, indeed it is very helpful.

Do you have plans to add currency code to each country. eg USD for United States of America, PLN for Poland etc

Cheers!

**Comment by frankodoom** [comment]
Yes, there is an update coming up with the Currency code.

**Comment by benjaminjnr** [comment]
It seems this issue is still open?

Are you down to get updates but incrementally?

**Comment by Clifftech123** [comment]
@benjaminjnr  Yes, we have added it to the upcoming version.
